### ISSUE TITLE
trainY25625616.csv

### ISSUE THREAD

**Issue by SunAnLan** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#1]

**Comment by SunAnLan** [comment]
Oh, I did not find the code to generate it. Finally I made one by myself according to the code which uses this csv

**Comment by junqiangchen** [comment]
> Oh, I did not find the code to generate it. Finally I made one by myself according to the code which uses this csv

ok,good luck

**Comment by Sempronius** [comment]
> Oh, I did not find the code to generate it. Finally I made one by myself according to the code which uses this csv

Would you consider sharing this code you wrote to generate the csv file?

**Comment by SunAnLan** [comment]
> > Oh, I did not find the code to generate it. Finally I made one by myself according to the code which uses this csv
> 
> Would you consider sharing this code you wrote to generate the csv file?
It is a pity that the code was not kept. However, I can send you that  csv if you need. plz leave your email

**Comment by SunAnLan** [comment]
It is a pity that the code was not kept. However, I can send you that  csv if you need. plz leave your email @Sempronius

**Comment by ethan19941022** [comment]
It is a pity that the code was not kept. However, I can send you that  csv if you need. plz leave your email @Sempronius
Please send it to me ,1210328691@qq.com. Thank you so much.

**Comment by Sempronius** [comment]
Thanks SunAnLan!, I managed to write something that worked out.
