### ISSUE TITLE
Time limit exceeded on lits challenge

### ISSUE THREAD

**Issue by seddik11** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#11]
hello,
yesterday i made a submission on codalab but after running a couple of hours i was surprised by a weird ''time limit exceeded" error do you have any idea about the origin of this error ? thank you

**Comment by cihan55555** [comment]
I think this issue is about codalab.Not about codes

**Comment by seddik11** [comment]
exactly someone else told me the same thing but what is the solution then ? codalab support told me to talk to the organizers of the competition to increase the time limit but at the same time i see some people succeed to make successful submission. even i'm making many attempts all the time no one worked for me ! this is so confusing..

**Comment by seddik11** [comment]
the problem is solved
