### ISSUE TITLE
Liver segmentation is good but this code is not finding tumor. Who find results?

### ISSUE THREAD

**Issue by cihan55555** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#13]

**Comment by sindhuchava** [comment]
Hi junqiangchen,

Thanks for providing the implementation.

Facing the same issue. Following the steps described, the results for liver segmentation is good but couldn't find good results for tumor segmentation. Can you provide any leads over this issue?

**Comment by junqiangchen** [comment]
hi,
finding tumor is same with finding liver,you should prepare tumor segmentation data and training another model.

**Comment by sindhuchava** [comment]
Hi junqiangchen,

Thanks for the response

From raw images, how can we prepare tumor segmentation data? 
If known, can you provide insight on accessing the images and if any annotation tools required for annotating the images?

**Comment by junqiangchen** [comment]
hi,
preparing liver tumor segmentation data is same with liver segmentation data,but liver tumor patch size is different from liver patch size.

**Comment by sindhuchava** [comment]
Hi,

Can you provide the liver tumor patch size for liver tumor segmentation?

**Comment by Kuailun** [comment]
Hi,
I have the same issue. Could you provide us some more information? Thanks!

**Comment by junqiangchen** [comment]
liver tumor patch size is 128x128x64, liver tumor patch size is 256x256x16

**Comment by Kuailun** [comment]
Thanks！


------------------
Kind Regards,
YuChen Chai


Phone: +86 13810293640
Web: https://www.fycyccreativehouse.com/





 




------------------ 原始邮件 ------------------
发件人: "junqiangchen"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 上午9:36
收件人: "junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge"<LiTS---Liver-Tumor-Segmentation-Challenge@noreply.github.com>;
抄送: "YuChen Chai"<593677394@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge] Liversegmentation is good but this code is not finding tumor. Who find results?(#13)




liver tumor patch size is 128x128x64, liver tumor patch size is 256x256x16

**Comment by sindhuchava** [comment]
Hi junqiangchen,

I have tried with a tumor patch size of 128x128x64, but facing some issues regarding shape.
Can you suggest what all changes need to be done in the code for patch size 128x128x64?

**Comment by junqiangchen** [comment]
> Hi junqiangchen,
> 
> I have tried with a tumor patch size of 128x128x24, but facing some issues regarding shape.
> "InvalidArgumentError (see above for traceback): Expected begin[1] in [0, 3], but got -1"
> 
> Can you suggest what all changes need to be done in the code for patch size 128x128x24?

Hi,
your patch size should reshape to 128x128x24x1

**Comment by zz10001** [comment]
Hi junqiangchen,
Thanks for your awesome work，I have some confused about `# step4: if stridez==0,return numberxy * numberxy * 2 samples,one is [0:blockz,:,:],two is [-blockz-1:-1,:,:]` **in getPatchImageAndMask.py line 82**,i can't understand what it mean.Can you explain it.thanks for your help!

**Comment by junqiangchen** [comment]
> Hi junqiangchen,
> Thanks for your awesome work，I have some confused about `# step4: if stridez==0,return numberxy * numberxy * 2 samples,one is [0:blockz,:,:],two is [-blockz-1:-1,:,:]` **in getPatchImageAndMask.py line 82**,i can't understand what it mean.Can you explain it.thanks for your help!

Hi,
this mean is if input image z size is almost same with subimage z size,so generate the two subimages with fixed z order images.

**Comment by zz10001** [comment]
> Hi,
> this mean is if input image z size is almost same with subimage z size,so generate the two subimages with fixed z order images.

Thank you for your reply!

**Comment by Kuailun** [comment]
Hi, I am testing the images basing your code(https://pan.baidu.com/s/1A_-u7tJcn7rIqnrLaSqi4A). May I ask the parameter for HU function(Preprocessing)


For example:
nii_image[nii_image<-200]=-200
nii_image[nii_image>250]=250
nii_image=(nii_image+200)*255/450


What is the range for your code? Thanks!


Besides, may I add you as a wechat friend?


------------------
Kind Regards,
YuChen Chai






 




------------------ 原始邮件 ------------------
发件人: "junqiangchen"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 上午9:36
收件人: "junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge"<LiTS---Liver-Tumor-Segmentation-Challenge@noreply.github.com>;
抄送: "YuChen Chai"<593677394@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge] Liversegmentation is good but this code is not finding tumor. Who find results?(#13)




liver tumor patch size is 128x128x64, liver tumor patch size is 256x256x16

**Comment by junqiangchen** [comment]
> Hi, I am testing the images basing your code(https://pan.baidu.com/s/1A_-u7tJcn7rIqnrLaSqi4A). May I ask the parameter for HU function(Preprocessing) For example: nii_image[nii_image<-200]=-200 nii_image[nii_image>250]=250 nii_image=(nii_image+200)*255/450 What is the range for your code? Thanks! Besides, may I add you as a wechat friend?
> […](#)
> ------------------ Kind Regards, YuChen Chai
> ------------------ 原始邮件 ------------------ 发件人: "junqiangchen"<notifications@github.com>; 发送时间: 2019年9月3日(星期二) 上午9:36 收件人: "junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge"<LiTS---Liver-Tumor-Segmentation-Challenge@noreply.github.com>; 抄送: "YuChen Chai"<593677394@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge] Liversegmentation is good but this code is not finding tumor. Who find results?(#13) liver tumor patch size is 128x128x64, liver tumor patch size is 256x256x16 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

sure,my wechat is 1207173174
