### ISSUE TITLE
Can this code support GPU parallel?

### ISSUE THREAD

**Issue by Mwzz** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#15]
I notice that the default GPU setting in this training code is :
_os.environ["CUDA_VISIBLE_DEVICES"] = "0"_ and _batch_size = 1_

when I simply change them to:
_os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3,4,5,6,7"_ and _batch_size = 8_
(since I have 8 GPUs)
OOM error happens

so can this code support GPU parallel naturally or should I modify it for mutli-GPU scenario?
my tf version is 1.8.0

Thank you!

**Comment by junqiangchen** [comment]
Hi，
this is project only can run on single GPU，if you want train the model on mutil GPUs, must rewrite the code that can run mutil GPUs,you can refer the project of https://github.com/junqiangchen/MutilGPU2dCNN,this is example of training mutil GPUs
thanks.
