### ISSUE TITLE
some questions about predict result

### ISSUE THREAD

**Issue by UCAS-Vincent** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#16]
my segmentation resullts of Liver is all white image,why?

**Comment by junqiangchen** [comment]
first,make sure the data is right when predicting,second,maybe the trained modal is not good!

**Comment by UCAS-Vincent** [comment]
Thank you, I made it.

**Comment by UCAS-Vincent** [comment]
How to process the bmp of the segmentation result into nii

**Comment by junqiangchen** [comment]
> How to process the bmp of the segmentation result into nii

hi,you can load all bmp into 3d array,and using simpleitk generate the nii file.
