### ISSUE TITLE
Download resource problem

### ISSUE THREAD

**Issue by amyou2005** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#17]
Dear, 
with the resources, I can't download because it all Chinese. I try to register but not allow any thai phone number. Could you help me?

liver segmentation trained model,log,test data can download on here:https://pan.baidu.com/s/1ijK6BG3vZM4nHwZ6S2yFiw, password：74j5
LiTS data have 130 cases,using 0-110 cases trainging,and other is testing.testing result can download on here:https://pan.baidu.com/s/1A_-u7tJcn7rIqnrLaSqi4A password：22es
LiTS train and test source data can download here:https://pan.baidu.com/s/1-kxJ7reS4kq5ypitfmQxeg password：nlrd

**Comment by junqiangchen** [comment]
hi,
if you can't download the trained model,you should follow the step to train the model by yourself.
thank you.

**Comment by amyou2005** [comment]
ok i will try thanks
