### ISSUE TITLE
about the number of sample

### ISSUE THREAD

**Issue by zgj834124621** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#20]
hello,thanks for your contribution.I want ask one question,as follow:
how do you sellect the number of sample which is in the getPatchImageAndMask.py.
I print the number of sample,which is 5917.I use the dataset of LITS.
Looking forward to hearing from you!

**Comment by junqiangchen** [comment]
hi,the LITS Data image size is 512x512xdim,i get patch images by fixed strides,sure you can modify it,if the dim is big,the samples number is big.
