### ISSUE TITLE
Result testing

### ISSUE THREAD

**Issue by JohnleeHIT** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#21]
Hello,  thanks for making your code public,  and your code is great,  I have run your code, but i couldn't  test my data on the LITS website,  Can you tell me how to do that? Thank you.

**Comment by junqiangchen** [comment]
hi,you should make sure the type of test result data is same as the training data.

**Comment by JohnleeHIT** [comment]
I double checked the data, and still can't submit, maybe the system has been closed.
