### ISSUE TITLE
Cuda version

### ISSUE THREAD

**Issue by SidGul** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#24]
Hi,
I have problem in train file that generates some error related to cuda. can you please tell which cuda version you have used?
Thanks

**Comment by junqiangchen** [comment]
> Hi,
> I have problem in train file that generates some error related to cuda. can you please tell which cuda version you have used?
> Thanks

Hi，My CUDA is V9.0，and tensorflow is 1.8.0
