### ISSUE TITLE
Preprocess time

### ISSUE THREAD

**Issue by Friday131** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#26]
How long does it take to run getPatchImageAndMask.py?

**Comment by junqiangchen** [comment]
> How long does it take to run getPatchImageAndMask.py?

hi,i don't calculate the running time,may be take several days

**Comment by francismontalbo** [comment]
Several days??!! How many images are going to be created for liver?

**Comment by life-8079** [comment]
”Process finished with exit code  (Interrupted by signal 9: sigkill)” appears when running getpatchimageandmask.py. The online query says that the CPU or running memory is insufficient. My running memory is 32g

**Comment by francismontalbo** [comment]
> ”Process finished with exit code (Interrupted by signal 9: sigkill)” appears when running getpatchimageandmask.py. The online query says that the CPU or running memory is insufficient. My running memory is 32g

32g will not be enough, unless you have extra disk space for paging.

**Comment by life-8079** [comment]
> 

thanks, I asked the author that he said his  running memory is 128g.

**Comment by life-8079** [comment]
> > 运行 getpatchimageandmask.py 时出现“Process finished with exit code (Interrupted by signal 9: sigkill)”。网上查询说CPU或者运行内存不足。我的运行内存是32g
> 
> 32g 是不够的，除非你有额外的磁盘空间用于分页。

Thanks, I asked the author that he said his running memory is 128g.
