### ISSUE TITLE
utils.py

### ISSUE THREAD

**Issue by klxlingxiang** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#27]
你好，我是一个刚入门，请问运行utils.py时出现了TypeError: object of type 'NoneType' has no len()这个错误是怎么回事？

**Comment by junqiangchen** [comment]
> 你好，我是一个刚入门，请问运行utils.py时出现了TypeError: object of type 'NoneType' has no len()这个错误是怎么回事？

你好，请确保输入的数据是有效数据
