### ISSUE TITLE
Performance issues in LiTS/data_input/dataset_input.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#28]
Hello,I found a performance issue in the definition of `datagenerator` ,
LiTS/data_input/dataset_input.py,
[dataset = dataset.map(_parse_function)](https://github.com/junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge/blob/b547eb42cab6e09a1a4bd86ad428c9e7d8a31cf8/LiTS/data_input/dataset_input.py#L107) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

The same issues also exist in [dataset = dataset.map(_preprocess_function)](https://github.com/junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge/blob/b547eb42cab6e09a1a4bd86ad428c9e7d8a31cf8/LiTS/data_input/dataset_input.py#L108)

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by junqiangchen** [comment]
thank you,if you can fix the problem that is good.
