### ISSUE TITLE
about original test data file  .nii 

### ISSUE THREAD

**Issue by tanggirltt** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#3]
您好，请问您可以提供.nii格式的原始测试数据吗？我在LITS挑战赛的官方网站上不能打开测试数据链接。
![image](https://user-images.githubusercontent.com/49739881/58561930-dabd0900-825a-11e9-8134-40a51a01f54e.png)

万分感谢!

**Comment by junqiangchen** [comment]
我记得把所有的训练和测试数据都放到百度云盘了，你看一下

**Comment by tanggirltt** [comment]
确实是有的，但是好像不是LiTS的那70个.nii格式的数据呀，您有原始数据吗？

**Comment by junqiangchen** [comment]
好的，我在找一下

**Comment by tanggirltt** [comment]
感谢大佬！
  

 

 ------------------ 原始邮件 ------------------
  发件人: "junqiangchen"<notifications@github.com>;
 发送时间: 2019年5月31日(星期五) 中午12:05
 收件人: "junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge"<LiTS---Liver-Tumor-Segmentation-Challenge@noreply.github.com>;
 抄送: "1448449285"<1448449285@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge] aboutoriginal test data file .nii (#3)

 

 
好的，我在找一下
