### ISSUE TITLE
Performance issue in /LiTS/data_input (by P3)

### ISSUE THREAD

**Issue by DLPerf** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#30]
Hello! I've found a performance issue in dataset_input.py: `dataset.batch(batch_size)`[(line 109)](https://github.com/junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge/blob/b547eb42cab6e09a1a4bd86ad428c9e7d8a31cf8/LiTS/data_input/dataset_input.py#L109) should be called before `dataset.map(_parse_function)`[(line 107)](https://github.com/junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge/blob/b547eb42cab6e09a1a4bd86ad428c9e7d8a31cf8/LiTS/data_input/dataset_input.py#L107) and `dataset.map(_preprocess_function)`[(line 108)](https://github.com/junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge/blob/b547eb42cab6e09a1a4bd86ad428c9e7d8a31cf8/LiTS/data_input/dataset_input.py#L108), which could make your program more efficient.

Here is [the tensorflow document](https://tensorflow.google.cn/guide/data_performance?hl=zh_cn#vectorized_mapping) to support it.

Besides, you need to check the function `_preprocess_function` called in `dataset.map(_preprocess_function)` whether to be affected or not to make the changed code work properly. For example, if `_preprocess_function` needs data with shape (x, y, z) as its input before fix, it would require data with shape (batch_size, x, y, z) after fix.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by DLPerf** [comment]
Hello, I'm looking forward to your reply~

**Comment by junqiangchen** [comment]
> Hello, I'm looking forward to your reply~

thank you for your suggestion，i have converted tf code to pytorch，and using pytorch dataset load the dataset，you can find the pytorch project from here:https://github.com/junqiangchen/PytorchDeepLearing
