### ISSUE TITLE
How to convert *.nii to *.bmp?  

### ISSUE THREAD

**Issue by hongson23** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#6]
Hello @junqiangchen,
Thank you for your project
I have tried to predict some data-set but results are not good.  
Maybe source image which is converted from *.nii file wrong.
I use [https://github.com/kirsebaer/nii2img](https://github.com/kirsebaer/nii2img) for convert *.nii to *.bmp
Could you please sharing code to convert .nii to .bmp image?

**Comment by junqiangchen** [comment]
hi,
you can use simpleitk load *.nii file and save ndarray into *.bmp file.
