### ISSUE TITLE
I can't run v3d_predict.py

### ISSUE THREAD

**Issue by cihan55555** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#7]
I got this error. "UnicodeEncodeError: 'utf-8' codec can't encode character '\udcfd' in position 3391: surrogates not allowed"

**Comment by junqiangchen** [comment]
hi，maybe the error is file format is incompatible,i use pycharm ide,you can try it.

**Comment by cihan55555** [comment]
Nope. It is not worked:(

**Comment by cihan55555** [comment]
I solved this problem by pycharm thank you. I have new issue :)

**Comment by cihan55555** [comment]
batch_xs[index, :, :] = imgs[128:384, 128:384]
TypeError: 'NoneType' object is not subscriptable

**Comment by junqiangchen** [comment]
the batch_xs size is different with imgs
