### ISSUE TITLE
How can I predict all part of patient's images and save video files?

### ISSUE THREAD

**Issue by cihan55555** [junqiangchen/LiTS---Liver-Tumor-Segmentation-Challenge#9]

**Comment by junqiangchen** [comment]
you can use cv2 video writer save images to video

**Comment by cihan55555** [comment]
Thank you. But I wonder that how can I merge patches . Because now we can predict patches but We can't merge results into one

**Comment by junqiangchen** [comment]
it is not difficult,the patch is ndarray type,you just merge the patches into one ndarray

**Comment by cihan55555** [comment]
I am new and I can't do that. İf this is easy. May be you can share the cod to merge pathces

**Comment by cihan55555** [comment]
ok I solved :)
